
import 'package:flutter/material.dart';
import 'bytestar_data.dart';

final List<Mission> runeCityCMissions = [
  Mission(
    id: 'rc1',
    title: 'Casting the First Rune',
    description: 'Bind energy to a name using C syntax.',
    concept: 'Variables',
    introVideoId: 'rune_intro_1',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'The city memory is fading.',
      'I am Luna, keeper of the runes.',
      'In C, we must declare the type of energy before binding it.',
      'We use "int" for whole numbers.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'int energy = 25;\nprintf("%d", energy);',
      steps: [
        TeachingStep(
          explanation: 'Declare an integer with "int".',
          highlightedLines: [1],
          visualAssetId: 'engine_start',
        ),
        TeachingStep(
          explanation: 'Use printf with "%d" to display numbers.',
          highlightedLines: [2],
          visualAssetId: 'brackets',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Create an int variable "energy" with value 10, then print it using printf("%d", energy);',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Write your code below\n    \n    return 0;\n}',
      correctOutput: '10',
      validationRules: [
        ValidationRule(pattern: 'int energy', errorMessage: 'Declare an int named "energy".'),
        ValidationRule(pattern: '10', errorMessage: 'Set energy to 10.'),
        ValidationRule(pattern: 'printf', errorMessage: 'Use printf to display the value.'),
      ],
      hints: ['int energy = 10;', 'printf("%d", energy);'],
    ),
    isLocked: false,
    x: 0.15,
    y: 0.85,
    languageId: 50,
    icon: Icons.bolt,
  ),
  Mission(
    id: 'rc2',
    title: 'Infinite Fountains',
    description: 'Automate city tasks with for loops.',
    concept: 'Loops',
    introVideoId: 'rune_intro_2',
    openingScene: SceneType.engineRoom,
    dialogueLines: [
      'The fountains need a steady pulse.',
      'C loops give us precise control over repetition.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'for (int i = 0; i < 3; i++) {\n    printf("Flow\\n");\n}',
      steps: [
        TeachingStep(
          explanation: 'The for loop has three parts: init, condition, and increment.',
          highlightedLines: [1],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: 'The code inside { } repeats.',
          highlightedLines: [2],
          visualAssetId: 'brackets',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Write a loop that prints "Glow" 3 times (with newlines).',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Write your code below\n    \n    return 0;\n}',
      correctOutput: 'Glow\nGlow\nGlow',
      validationRules: [
        ValidationRule(pattern: 'for', errorMessage: 'Use a for loop.'),
        ValidationRule(pattern: 'i < 3', errorMessage: 'Repeat exactly 3 times.'),
        ValidationRule(pattern: 'printf', errorMessage: 'Print "Glow\\n" inside the loop.'),
      ],
      hints: ['for(int i=0; i<3; i++)', 'printf("Glow\\n");'],
    ),
    isLocked: true,
    x: 0.25,
    y: 0.75,
    languageId: 50,
    icon: Icons.loop,
  ),
  Mission(
    id: 'rc3',
    title: 'The Gate Keeper',
    description: 'Decide the city\'s fate with if-else.',
    concept: 'Conditions',
    introVideoId: 'rune_intro_3',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'The gate only opens for high energy.',
      'Conditions allow the runes to judge the signal.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'int energy = 60;\nif (energy > 50) {\n    printf("Open");\n} else {\n    printf("Hold");\n}',
      steps: [
        TeachingStep(
          explanation: 'if checks if a condition is true.',
          highlightedLines: [2, 3],
          visualAssetId: 'engine_start',
        ),
        TeachingStep(
          explanation: 'else runs if it is false.',
          highlightedLines: [4, 5],
          visualAssetId: 'check_mark',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'If energy is greater than 50, print "Open". Otherwise print "Hold".',
      initialCode: '#include <stdio.h>\n\nint main() {\n    int energy = 60;\n    // Write your code below\n    \n    return 0;\n}',
      correctOutput: 'Open',
      validationRules: [
        ValidationRule(pattern: 'if', errorMessage: 'Use an if statement.'),
        ValidationRule(pattern: '>', errorMessage: 'Check if energy is greater than 50.'),
        ValidationRule(pattern: 'printf', errorMessage: 'Display the result.'),
      ],
      hints: ['if (energy > 50)', 'printf("Open");'],
    ),
    isLocked: true,
    x: 0.35,
    y: 0.85,
    languageId: 50,
    icon: Icons.alt_route,
  ),
  Mission(
    id: 'rc4',
    title: 'Spell Crafting',
    description: 'Encapsulate logic in C functions.',
    concept: 'Functions',
    introVideoId: 'rune_intro_4',
    openingScene: SceneType.engineRoom,
    dialogueLines: [
      'Repeating spells is inefficient.',
      'In C, we define a return type and parameters for our functions.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'void shield() {\n    printf("Shield Up\\n");\n}\n\nint main() {\n    shield();\n    return 0;\n}',
      steps: [
        TeachingStep(
          explanation: 'void means the function returns nothing.',
          highlightedLines: [1],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: 'Call the function inside main.',
          highlightedLines: [6],
          visualAssetId: 'engine_start',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Define a function "shield" that prints "Shield Up". Then call it in main.',
      initialCode: '#include <stdio.h>\n\n// Define function here\n\nint main() {\n    // Call function here\n    return 0;\n}',
      correctOutput: 'Shield Up',
      validationRules: [
        ValidationRule(pattern: 'void shield', errorMessage: 'Define a void function named shield.'),
        ValidationRule(pattern: 'printf', errorMessage: 'Print "Shield Up".'),
        ValidationRule(pattern: 'shield()', errorMessage: 'Call shield() in main.'),
      ],
      hints: ['void shield() { ... }', 'shield();'],
    ),
    isLocked: true,
    x: 0.45,
    y: 0.75,
    languageId: 50,
    icon: Icons.auto_fix_high,
  ),
  Mission(
    id: 'rc5',
    title: 'Array of Runes',
    description: 'Store multiple readings in arrays.',
    concept: 'Arrays',
    introVideoId: 'rune_intro_5',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'The city reads many values at once.',
      'Arrays in C store elements of the same type in order.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'int levels[3] = {10, 20, 30};\nprintf("%d", levels[0]);',
      steps: [
        TeachingStep(
          explanation: 'Declare an array with a fixed size.',
          highlightedLines: [1],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: 'Access elements using [index].',
          highlightedLines: [2],
          visualAssetId: 'brackets',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Create an int array "nums" with values {1, 2, 3} and print the first element.',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Write your code below\n    \n    return 0;\n}',
      correctOutput: '1',
      validationRules: [
        ValidationRule(pattern: 'int nums', errorMessage: 'Declare an int array named "nums".'),
        ValidationRule(pattern: '{1, 2, 3}', errorMessage: 'Initialize with {1, 2, 3}.'),
        ValidationRule(pattern: 'nums[0]', errorMessage: 'Access index 0.'),
      ],
      hints: ['int nums[] = {1, 2, 3};', 'printf("%d", nums[0]);'],
    ),
    isLocked: true,
    x: 0.55,
    y: 0.85,
    languageId: 50,
    icon: Icons.view_list,
  ),
  Mission(
    id: 'rc6',
    title: 'Echoes of the Past',
    description: 'Interact with the city using scanf.',
    concept: 'User Input',
    introVideoId: 'rune_intro_6',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'The runes react to your touch.',
      'Use scanf to receive input from the terminal.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'int code;\nscanf("%d", &code);\nprintf("Received: %d", code);',
      steps: [
        TeachingStep(
          explanation: 'The & symbol (ampersand) is used to get the memory address of a variable.',
          highlightedLines: [2],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: 'scanf needs %d for integers, just like printf.',
          highlightedLines: [2],
          visualAssetId: 'engine_start',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Wait, I will provide the input "42". You must read it into an int "val" and print "Code 42".',
      initialCode: '#include <stdio.h>\n\nint main() {\n    int val;\n    // Write scanf and printf below\n    \n    return 0;\n}',
      correctOutput: 'Code 42',
      validationRules: [
        ValidationRule(pattern: 'scanf', errorMessage: 'Use scanf to read input.'),
        ValidationRule(pattern: '&val', errorMessage: 'Remember the & before val in scanf.'),
        ValidationRule(pattern: 'printf', errorMessage: 'Print "Code %d" (or "Code 42").'),
      ],
      hints: ['scanf("%d", &val);', 'printf("Code %d", val);'],
    ),
    isLocked: true,
    x: 0.65,
    y: 0.75,
    languageId: 50,
    icon: Icons.keyboard,
  ),
  Mission(
    id: 'rc7',
    title: 'Nested Leylines',
    description: 'Master nested loops for grid scanning.',
    concept: 'Nested Loops',
    introVideoId: 'rune_intro_7',
    openingScene: SceneType.engineRoom,
    dialogueLines: [
      'The runic grid is two-dimensional.',
      'A loop inside a loop can scan every point on the Leyline.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'for (int i=0; i<2; i++) {\n    for (int j=0; j<2; j++) {\n        printf("#");\n    }\n}',
      steps: [
        TeachingStep(
          explanation: 'The outer loop starts, then the inner loop finishes all its turns.',
          highlightedLines: [1, 2],
          visualAssetId: 'brackets',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Print a 2x2 grid of stars "**\\n**\\n" using nested loops.',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Use nested for loops\n    \n    return 0;\n}',
      correctOutput: '**\n**\n',
      validationRules: [
        ValidationRule(pattern: 'for', errorMessage: 'Use nested for loops.'),
        ValidationRule(pattern: '\\\\n', errorMessage: 'Remember the newline after each row.'),
      ],
      hints: ['for(int i=0; i<2; i++) { for(int j=0; j<2; j++) { printf("*"); } printf("\\n"); }'],
    ),
    isLocked: true,
    x: 0.75,
    y: 0.65,
    languageId: 50,
    icon: Icons.grid_4x4,
  ),
  Mission(
    id: 'rc8',
    title: 'Soul of Memory',
    description: 'Understand Pointers and Addresses.',
    concept: 'Pointers',
    introVideoId: 'rune_intro_8',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'A rune is just a marker for a place in memory.',
      'A pointer stores the address where the data lives.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'int n = 7;\nint *ptr = &n;\nprintf("%d", *ptr);',
      steps: [
        TeachingStep(
          explanation: 'int *ptr declares a pointer to an integer.',
          highlightedLines: [2],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: '*ptr (dereferencing) gets the value at that address.',
          highlightedLines: [3],
          visualAssetId: 'engine_start',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Declare an int "x" = 5. Create a pointer "p" to "x". Print the value of "x" using the pointer.',
      initialCode: '#include <stdio.h>\n\nint main() {\n    int x = 5;\n    // Create pointer p and print *p\n    \n    return 0;\n}',
      correctOutput: '5',
      validationRules: [
        ValidationRule(pattern: 'int *p', errorMessage: 'Declare a pointer int *p.'),
        ValidationRule(pattern: '&x', errorMessage: 'Point p to the address of x (&x).'),
        ValidationRule(pattern: '*p', errorMessage: 'Use *p to access the value.'),
      ],
      hints: ['int *p = &x;', 'printf("%d", *p);'],
    ),
    isLocked: true,
    x: 0.85,
    y: 0.55,
    languageId: 50,
    icon: Icons.touch_app,
  ),
  Mission(
    id: 'rc9',
    title: 'Whispering Winds',
    description: 'Handle text with character arrays.',
    concept: 'Strings',
    introVideoId: 'rune_intro_9',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'Words are just chains of characters.',
      'In C, a string is a char array ending with a null terminator \\0.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'char name[] = "Luna";\nprintf("%s", name);',
      steps: [
        TeachingStep(
          explanation: 'char type is used for single characters.',
          highlightedLines: [1],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: '%s is the format specifier for strings.',
          highlightedLines: [2],
          visualAssetId: 'engine_start',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Create a char array "msg" with "Fire" and print it using %s.',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Create msg and print\n    \n    return 0;\n}',
      correctOutput: 'Fire',
      validationRules: [
        ValidationRule(pattern: 'char msg', errorMessage: 'Declare a char array "msg".'),
        ValidationRule(pattern: 'Fire', errorMessage: 'Initialize with "Fire".'),
        ValidationRule(pattern: '%s', errorMessage: 'Use %s to print.'),
      ],
      hints: ['char msg[] = "Fire";', 'printf("%s", msg);'],
    ),
    isLocked: true,
    x: 0.75,
    y: 0.45,
    languageId: 50,
    icon: Icons.text_fields,
  ),
  Mission(
    id: 'rc10',
    title: 'The Blueprint',
    description: 'Group values into Structs.',
    concept: 'Structs',
    introVideoId: 'rune_intro_10',
    openingScene: SceneType.cockpit,
    dialogueLines: [
      'A Citizen is more than just a name.',
      'Structs allow us to bundle different data types together.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'struct Rune {\n    int power;\n    char id;\n};\n\nstruct Rune r1 = {100, \'A\'};',
      steps: [
        TeachingStep(
          explanation: 'Define the structure blueprint first.',
          highlightedLines: [1, 2, 3, 4],
          visualAssetId: 'toolbox',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Define a struct "Point" with ints "x" and "y". Create a Point "p" with {3, 4} and print x.',
      initialCode: '#include <stdio.h>\n\nstruct Point {\n    int x, y;\n};\n\nint main() {\n    // Create Point p and print p.x\n    \n    return 0;\n}',
      correctOutput: '3',
      validationRules: [
        ValidationRule(pattern: 'struct Point p', errorMessage: 'Declare a Point variable p.'),
        ValidationRule(pattern: 'p.x', errorMessage: 'Access current x with p.x.'),
      ],
      hints: ['struct Point p = {3, 4};', 'printf("%d", p.x);'],
    ),
    isLocked: true,
    x: 0.65,
    y: 0.35,
    languageId: 50,
    icon: Icons.settings_suggest,
  ),
  Mission(
    id: 'rc11',
    title: 'Final Scroll',
    description: 'Write to the Great Archive.',
    concept: 'File I/O',
    introVideoId: 'rune_intro_11',
    openingScene: SceneType.engineRoom,
    dialogueLines: [
      'Rune City must remember its heroes.',
      'Files allow us to save our magic even after the city resets.',
    ],
    teachingModule: const TeachingModule(
      codeSnippet: 'FILE *f = fopen("rune.txt", "w");\nfprintf(f, "Magic");\nfclose(f);',
      steps: [
        TeachingStep(
          explanation: 'fopen opens a file. "w" means write mode.',
          highlightedLines: [1],
          visualAssetId: 'toolbox',
        ),
        TeachingStep(
          explanation: 'fprintf writes to the file pointer instead of the screen.',
          highlightedLines: [2],
          visualAssetId: 'engine_start',
        ),
      ],
    ),
    task: const CodingTask(
      instruction: 'Write "Hero" to "log.txt" using fopen, fprintf, and fclose. (Output "Hero" for confirmation)',
      initialCode: '#include <stdio.h>\n\nint main() {\n    // Mock note: just print "Hero" to pass simulation\n    printf("Hero"); \n    return 0;\n}',
      correctOutput: 'Hero',
      validationRules: [
        ValidationRule(pattern: 'FILE', errorMessage: 'Use FILE pointer.'),
        ValidationRule(pattern: 'fopen', errorMessage: 'Open the file.'),
        ValidationRule(pattern: 'fclose', errorMessage: 'Dont forget to close the file.'),
      ],
      hints: ['FILE *fp = fopen("log.txt", "w");', 'fprintf(fp, "Hero");', 'fclose(fp);'],
    ),
    isLocked: true,
    x: 0.55,
    y: 0.25,
    languageId: 50,
    icon: Icons.save,
  ),
];
